# Generated by Django 2.2.7 on 2019-11-28 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vmachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('littleEndian', models.BooleanField(default=True, null=True)),
                ('instancePath', models.CharField(max_length=50)),
                ('create_date', models.DateField(null=True)),
                ('architecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Architecture')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('hash', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('instancePath', models.CharField(max_length=200)),
                ('analisis', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('Vmachine_dst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Vmachine')),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Familia')),
            ],
        ),
    ]
