# Generated by Django 2.2.7 on 2019-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='architecture',
            field=models.CharField(default='arm_32', max_length=30),
        ),
    ]
