# Generated by Django 2.2.7 on 2019-11-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_muestra_architecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='instancePath',
        ),
        migrations.AddField(
            model_name='muestra',
            name='static_anal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='analisis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familyid', to='web.Familia'),
        ),
    ]
