# Generated by Django 2.2.7 on 2019-11-29 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191129_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
